//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangWebTuVanSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTIONNOTCHECK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTIONNOTCHECK()
        {
            this.QUESTIONQUEUEs = new HashSet<QUESTIONQUEUE>();
        }
    
        public int QuestionID { get; set; }
        public Nullable<int> IDStu { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDField { get; set; }
        public string Question { get; set; }
        public Nullable<bool> Checked { get; set; }
    
        public virtual FIELD FIELD { get; set; }
        public virtual QUESTIONANDANSWER QUESTIONANDANSWER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONQUEUE> QUESTIONQUEUEs { get; set; }
    }
}
