//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangWebTuVanSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTIONANDANSWER
    {
        public int QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<System.DateTime> DateOfAnswer { get; set; }
        public Nullable<int> IDField { get; set; }
        public string Question { get; set; }
    
        public virtual FIELD FIELD { get; set; }
        public virtual QUESTIONNOTCHECK QUESTIONNOTCHECK { get; set; }
    }
}
