//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangWebTuVanSinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTIONQUEUE
    {
        public int IDField { get; set; }
        public int QuestionID { get; set; }
        public Nullable<System.DateTime> DateOfModeration { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Question { get; set; }
    
        public virtual FIELD FIELD { get; set; }
        public virtual QUESTIONNOTCHECK QUESTIONNOTCHECK { get; set; }
        public virtual USER USER { get; set; }
    }
}
